---
#this line is because ubuntu 16.04 doesn't have python and we need connect in mode raw
- name: Bootstrap a legacy python 2.4 host
  raw: apt-get install python-simplejson -y

- name: Install dependencies
  apt: name={{ item }} state=latest update_cache=yes
  with_items: "{{ packages_to_install }}"

- name: Create folder to unarchive the AWS utilites
  file: path={{ aws_scripts_path }} state=directory mode=0644

- name: Unarchive aws monitoring scripts from  URL
  unarchive:
    src: http://aws-cloudwatch.s3.amazonaws.com/downloads/CloudWatchMonitoringScripts-1.2.1.zip
    dest: /opt
    remote_src: yes

- name: Copy config template
  template: src=awscreds.j2 dest={{ aws_scripts_path }}/awscreds.conf

- cron:
    name: "Check memory and disk"
    minute: "*/2"
    job: "{{ aws_scripts_path }}/mon-put-instance-data.pl --mem-avail --mem-util --disk-space-util --disk-path=/ --disk-space-avail --from-cron > /dev/null"
    state: present
