---
- name: Add an Apt key for Docker CE
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Adding Docker CE repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu xenial stable
    state: present

- name: Update repositories cache and install "Docker CE" package
  apt:
    name: docker-ce

- name: Restart docker service
  service: name=docker state=restarted

#- name: Installing configuration file
#  template: src=templates/mongod.conf.j2 dest=/etc/mongod.conf mode=0644
